### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by sndrs** [hemanth/postcss-longhand#1]
Hi there,

I'm really keen to use this in a kind of atomic css module thing I'm trying at the guardian, but I'm hitting an  error, does it look familiar to you?

in:

``` css
.nav {
  width: 100%;
  height: 16px;
  margin-top: 1rem;
  padding: 2rem;
  transition: all;
  font-family: "Helvetica Neue", Arial, Arial, sans-serif;
  font-weight: normal; }
  .nav:hover {
    height: 32px; }
```

out:

``` css
.nav {
  width: 100%;
  height: 16px;
  margin-top: 1rem;
  padding: .nav {
  width: 100%;
  height: 16px;
  margin-top: 1rem;
  padding-top: 2rem;
  padding-right: 2rem;
  padding-bottom: 2rem;
  padding-left: 2rem;
  transition: all;
  font-family: "Helvetica Neue", Arial, Arial, sans-serif;
  font-weight: normal; }
  .nav:hover {
    height: 32px; }
```

it's almost there! any ideas?

using the following versions in `package.json`, in node 6:

``` json
    "postcss": "^5.0.19",
    "postcss-longhand": "^1.0.0"
```

thanks for your help!
